### ISSUE TITLE
Build depends on older OCaml version

### ISSUE THREAD

**Issue by titzer** [WebAssembly/exception-handling#144]
While the mainline spec repo has moved onto OCaml version 4.10, this repo still depends on an earlier version. This makes it hard to work on multiple proposals at once.

Can we rebase this repo on the current spec repo?

**Comment by ioannad** [comment]
@aheejin: I could take care of this rebase, but I have one question. Should I rebase on the current main spec repo or on the reference types repo? So far we have updated the repo to follow reference types, so it's straightforward to update to this again.

- On the one hand, it's probable (@rossberg: is it?) that reference-types will reach stage 5 soon, so if I update to keep following the reference-types repo we would avoid an unnecessary messy merge now.
- On the other hand, reference types is no longer a dependency, so technically now I should update to the main repo instead, but this update might get messy. 

I would be ok with either option. WDYT?

> This makes it hard to work on multiple proposals at once.

By the way, @titzer, your comment above seems to indicate you might be working on the interpreter or the tests, is this the case?

**Comment by rossberg** [comment]
Landing reftypes into the main spec has been announced and should merely be a question of waiting out the 10 day period of objection required by the charter. So you could just wait for that.

On the other hand, you'll have to do the same work either way. The reftypes repo is in sync with the main repo, so if you merge that now, then the later merge with main should require no extra work anymore. In fact, I suspect that merging from the reftypes repo first might be easier, since that has the history unsquashed, so git might have an easier time resolving things automatically. But that is just a guess based on my naive understanding of how git merges work.

**Comment by ioannad** [comment]
@rossberg It was pretty straightforward indeed to just `git merge reference-types/master` at this stage (PR #148). Congratulations on having reference-types standardised!
