### ISSUE TITLE
Exception section position and identifier

### ISSUE THREAD

**Issue by eholk** [WebAssembly/exception-handling#25]
The proposal does not list a section id for the exception section. Based on [this change to V8](https://chromium-review.googlesource.com/c/591910/7/src/wasm/module-decoder.h#37), I assume this should be 13?

It looks like the exception section must come before the code section, so sections no longer come strictly in order (modulo custom sections). How precisely should we specify the location of the exception section?

**Comment by titzer** [comment]
IMO the exception section should have a well-specified order, even though it might not match the ID. Current decoders were designed with this forward-looking assumption, since they simply do something like:

if (section_code == kFirstCode) {
  readFirstSection();
  section_code = next_code();
}
if (section_code == kSecondCode) {
  readSecondSection();
  section_code = next_code();
} 
...

The actual numerical values of the section codes were expected to get out of order.

**Comment by aheejin** [comment]
Closed by #62 and #75.
