### ISSUE TITLE
Stack trace without importing JS API

### ISSUE THREAD

**Issue by Yu-zh** [WebAssembly/exception-handling#320]
Hello! I was wondering whether it is possible that exceptions thrown by the wasm instruction `throw` can carry stack traces. After reading the document and examples, it seems that the only way to throw exception with stack traces is to import a JS API to do that. Is that right?

**Comment by dschuff** [comment]
Yes, that is currently the case. This was done because exceptions are sometimes used as more-general nonlocal control flow (so they are "unexceptional"), so we didn't want to incur the cost of collecting a stack trace on every throw by default. Also there's not a good way in core wasm to specify what a stack trace would do, since it wouldn't have observable semantics. This is something that we might be able to fix in the future, but isn't part of this proposal.
