### ISSUE TITLE
Should we model exception constructors using existing functions?

### ISSUE THREAD

**Issue by KarlSchimpf** [WebAssembly/exception-handling#5]
After reading a lot of the feedback, I am beginning to think that the notion of an "exception section" is unnecessary to implement exception handling.

What I propose to do instead is to use "thow" and "catch" opcodes that immediately precedes a call instruction, creating new constructs.

The throw construct calls the call instruction to build the exception, which is an internal record with
the following fields:

(1) The function called to construct the exception.
(2) The value(s) returned by the called function.

A catch prefix doesn't call the function. Rather it is used to match field (1) of the exception. If it matches, the catch block is run. Before running, the value(s) of field (2) are pushed on the block.

Note that the default catch (an else clause in a try block) would apply if none of the other catch constructs match.

This solution has the advantage that we don't introduce new sections to the module. The existing framework already handles all the important parts, other than modeling a WASM exception.

Further, all exceptions, including those not produced by WASM, can be represented this way. One
just needs to build a record that has an appropriate function pointer for field (1), and any accessable values in field (2).

Is this a viable way to implement exception?

**Comment by flagxor** [comment]
How would this handle importing and exporting exceptions?
We need some mechanism for mixed language programs to tell apart exceptions with the same signature.

**Comment by KarlSchimpf** [comment]
The constructor functions are just imported/exported!

Karl Schimpf

**Comment by KarlSchimpf** [comment]
The exception is an object, not a function, and is internal to the exception. Exceptions are importable/exportable iff their constructors are.

Alternatively, we could still be explicit by adding an "exception" import that references the corresponding constructor function.

**Comment by KarlSchimpf** [comment]
That is, keep a new "external_kind" 'exception', For imports, it is the corresponding function signature being imported. For exports, it is the function index of the exception constructor function.

**Comment by flagxor** [comment]
The prefixes sound less dense than using new opcodes for each, which I suspect we can afford.
Perhaps reusing aspects of the definition of calls, but not the actual opcodes makes sense?

I can see how you might import a function that take basic types and returns an exception, but how does it work at the call site?

**Comment by rossberg** [comment]
Hm, I don't understand. Are you proposing that `throw` executes the call? If so, how does the function "return" the exception? Or if it doesn't return it, how does it initialise it? Or are you suggesting that no call is actually performed? But why use fake call instructions then? And when you catch an exception, how do you identify it? Do functions acquire an identity? Does an implementation need to equip all of them with a tag value somehow, in case some other module wants to use them as an exception later?

Exceptions and functions are different beasts. Exceptions are simply a data structure (a tuple with a generative tag, no associated code) that gets initialised and accessed. Crucially, their tag provides some sort of explicit identity. Functions OTOH encapsulate code that gets executed and produces a result. They don't currently have an observable identity in Wasm. So both notions are pretty much disjoint. The only commonality between the two is that they both have a list of "parameters".

**Comment by AndrewScheidecker** [comment]
I agree that the exception section, and imported/exported exception tags seems unnecessary. Dynamic linking of exception tags can be left up to language-specific ABIs.

> The throw construct calls the call instruction to build the exception, which is an internal record with
the following fields:
>
>(1) The function called to construct the exception.
>(2) The value(s) returned by the called function.
>
>A catch prefix doesn't call the function. Rather it is used to match field (1) of the exception. If it matches, the catch block is run. Before running, the value(s) of field (2) are pushed on the block.

I think this could be simplified by just using some integer to tag the exception instead of a function reference:

`throw` and `catch` are matched by an arbitrary `i32` tag and a function signature. Negative tag values would be reserved for exceptions generated by the runtime, and positive tag values would be allocated by some ABI-specific scheme. Perhaps those could be surfaced to JavaScript as a WebAssemblyException(i32,...).

In an uninstantiated module, the signature is encoded by the `throw` and `catch` operators as an index into the module's type table. It might be necessary to add a new constructor for exception signatures to the type table, or to require that the indexed function type has no result. The `throw` operator pops the signature's parameters from the operand stack, and the `catch` operator pushes them.

**Comment by rossberg** [comment]
@AndrewScheidecker, we arrived at the current design because it was observed that an integer is not good enough as an exception tag: a transparent int cannot reliably prevent clashes between exceptions defined in unrelated modules (which could pass by each other's catch handlers even if they can't see their respective definitions). It thus is important that exceptions can be locally ensured to have a globally unique identity. Moreover, for modular encapsulation, it is also desirable that a module can only throw (and destructure) exceptions whose definitions it can access, analogous to other definitions.

That requires that exceptions are defined in a generative manner, that they can be exported/imported, and that they cannot be forged. A primitive mechanism seems like the only reliable and portable way to achieve that.

An additional advantage of the generative scheme is that different exceptions can carry different attribute types, which wouldn't be type-safe otherwise (or would require brittle use of global state).

**Comment by AndrewScheidecker** [comment]
>we arrived at the current design because it was observed that an integer is not good enough as an exception tag: a transparent int cannot reliably prevent clashes between exceptions defined in unrelated modules (which could pass by each other's catch handlers even if they can't see their respective definitions).

It seems pretty similar to dynamic linking of indirect function indices, which is left up to the ABI. An example ABI would be to import all the tags as `i32` globals with a name in a certain format, and when the linker sees a name in that format, it allocates a unique index to it (or reuses an existing index that has been allocated to the name), and binds that index to the import.

> That requires that exceptions are defined in a generative manner, that they can be exported/imported, and that they cannot be forged. A primitive mechanism seems like the only reliable and portable way to achieve that.

It doesn't seem important that exception tags are unforgeable.

However, maybe this could be unified with whatever scheme the GC proposal needs for nominal types: instead of adding a new definition/import kind for exceptions, add a new definition/import kind for "tags", and use them for both exception tags and as value types to in GC types to distinguish types that are otherwise structurally equivalent.

> An additional advantage of the generative scheme is that different exceptions can carry different attribute types, which wouldn't be type-safe otherwise (or would require brittle use of global state).

The scheme I described is still type-safe: it checks both the function signature and the tag. The throw can statically verify the types of its operands from the function signature, and the catch is only matched if the catch signature matches the throw signature.

**Comment by rossberg** [comment]
@AndrewScheidecker, there are two sides of the problem: _supporting_ intentional cross-module use of exceptions, and _preventing_ accidental cross-module clobbering or leakage. Note that both are independent of _dynamic_ linking, so neither a table nor a dynamic ABI should be required to solve the basic problem.

I don't understand how the scheme you propose could be type-safe. That would require establishing a globally unique bijection between integer tags and attribute types. How could that be enforced and checked? Or are you suggesting that an exception would carry runtime type information?

**Comment by AndrewScheidecker** [comment]
>  there are two sides of the problem: supporting intentional cross-module use of exceptions, and preventing accidental cross-module clobbering or leakage. Note that both are independent of dynamic linking, so neither a table nor a dynamic ABI should be required to solve the basic problem.

I see what you mean, and I concur that it seems like you need some kind of importable/exportable opaque tag values to solve that problem. However, the problem seems higher-level than the other problems WASM tries to solve.

> I don't understand how the scheme you propose could be type-safe. That would require establishing a globally unique bijection between integer tags and attribute types.

No:

> How could that be enforced and checked? Or are you suggesting that an exception would carry runtime type information?

Yes, the exception would have both a tag and the globally-uniqued ID of its argument signature (as is used to dynamically check the signatures of functions in tables on call). The catch handler would also have a tag and the globally-uniqued ID of its parameter signature. A catch would only catch an exception if both the tag and the signature ID matched.

This would avoid the need to maintain a globally unique bijection between tags and exception argument signatures, but introduce overloaded exception signatures as a side-effect. This really only makes sense if you use transparent `i32` tags, though. If you're going to introduce a nominal exception type constructors, it doesn't save much to factor the argument types out of it.

**Comment by KarlSchimpf** [comment]
There appears to be too many issues/constraints on how exceptions are built with this proposal. I suggest that we close this issue, and leave the proposal as is.

**Comment by KarlSchimpf** [comment]
Closing this issue, as the proposal doesn't consider this. If you feel the proposal should, feel free to reopen.
