### ISSUE TITLE
Does the current design of `catch` and `if_except` require `pick`?

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/exception-handling#50]
IIUC, `catch` pushes the `except_ref` value on the stack and `if_except` reads it from the top of the stack.  I was thinking that, in general, code generators may need to access the `except_ref` value when it's not at the top of the stack.  Normally, this is achieved by storing values in locals and using `get_local`.  `pick` could achieve the same for `except_ref` values on the stack, so should this proposal depend on (or smuggle in) `pick`?

**Comment by eholk** [comment]
I expect in practice producers will follow `catch` with a `tee_local` to stash the exception in a local variable, and similarly within the `if_except`.

There's no reason for this proposal to depend on `pick`, and in the interest of proposal hygiene, I'd argue against trying to smuggle it in. That said, I'd be supportive of adding `pick` or something similar to WebAssembly independently.

**Comment by aheejin** [comment]
Now that `except_ref` values share the same wasm value stack with other types, I guess it would be a little weird if only `except_ref` has `pick` instruction? If `pick` only supports `except_ref`, how would its semantic look like? Or do you mean we can have `pick` for any value types?

And `catch` is going to be followed by `if_except` that pops the `except_ref` object, so in this case the `except_ref` value that the `if_except` needs will be always on top of the stack.

And I guess the other reason you suggested this is for `rethrow`, in case `rethrow` throws an `except_ref` value that's not on top of the stack.
1. I checked clang and in the current clang code generator it is guaranteed that `rethrow` always throws an exception that is most recently thrown
2. But actually this is not relevant because now `except_ref` shares the wasm value stack with all other types, at the point of `rethrow` it is likely there are other values (i32, f32, ..) on the stack anyway
3. The current LLVM backend does not make use of the multi-value proposal, so if a `rethrow` is outside of a catch block, the `except_ref` on the stack is gone anyway (so we should use `get_local` and `set_local`). Actually it is gonna be popped by `if_except` right after a `catch`.

**Comment by lukewagner** [comment]
Oh, hah, right, I forgot that you could just immediately `set_local`/`tee_local` to get a copy of the `except_ref` value into a local.  n/m then :)
