### ISSUE TITLE
Use `else` opcode instead of `catch`?

### ISSUE THREAD

**Issue by binji** [WebAssembly/exception-handling#53]
I seem to recall that an older version of this proposal used the `else` opcode to mean `catch_all`. Seems like we could do that for `catch` now, since there's only ever one catch block. What do you think?

**Comment by KarlSchimpf** [comment]
I don't like 'else' because that seems to imply to me that instructions in the try block are not executed.

**Comment by rossberg** [comment]
@KarlSchimpf, let's not confuse binary encoding (which is just a serialisation format) with abstract syntax or text format. We could well call it `catch` there.

@titzer, don't you have that code anyway? You always need to check what's on top of the control stack, it would just become a switch instead of a single-armed if. They could probably even share some code.

**Comment by titzer** [comment]
@rossberg The decoder only matches `else` with `if`. There are three cases.

1.) `else` with no matching `if` => error
2.) `else` matching `if` with a previous `else` => error
3.) `else` matches an `if` (no previous else) => OK

So besides error checking, `else` only matches with `if`. I don't see any benefit to making it match with `try`.

**Comment by rossberg** [comment]
@titzer, you either get an additional case here or in the surrounding switch (then with the analog of the above 3 subcases repeated). The (minor) advantage of having it here is that it may allow sharing some code and that it saves an opcode.

Saving an opcode is perhaps irrelevant for a single instruction, but there are multiple other branch-like instructions on the horizon, e.g. the exception proposal also has a separate tag-checking instruction that has two branches, and with reference types we'll eventually have a down cast instruction that has two branches. Instead of introducing a multitude of separator opcodes it might make sense to have one generic one, in the same way we have one generic terminator.

**Comment by aheejin** [comment]
I'm personally OK either way, but this discussion kind of stopped and the spec and the engine/toolchain implementations use the new opcode (0x07) for `catch` now, so I'll close this for now. Please feel free to reopen if necessary.
