### ISSUE TITLE
event section ID

### ISSUE THREAD

**Issue by binji** [WebAssembly/exception-handling#70]
The event section is currently specified as id 12. The bulk memory proposal is also going to add a new section (see https://github.com/WebAssembly/bulk-memory-operations/pull/42), and will likely ship first. Should it have 12 instead so we don't have a gap in the known section ids? Or does it even matter?

**Comment by aheejin** [comment]
I don't think it matters a lot, but it may look weird. I don't mind change the event section to 13. We need to change the spec text, LLVM implementation, and V8 implementation. I can take care of the first two. @mstarzinger, could you change the event section ID in V8?

**Comment by mstarzinger** [comment]
Yes, that is an easy change. Coincidentally it used to be 13 in V8 until a couple of days ago because I originally chose the value at random before it was specified in the proposal. I'll keep V8 updated. Easy change similar to this one: https://chromium.googlesource.com/v8/v8/+/69ab6954b12091b7252ad79d5e940a9ed4244841

**Comment by aheejin** [comment]
LLVM change: https://reviews.llvm.org/D55343

**Comment by aheejin** [comment]
V8 change: https://chromium-review.googlesource.com/c/v8/v8/+/1478207
